// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCLs2aFsjtWCSRsdv_vwQdMNAG8JEZDHQ',
    appId: '1:25308580160:web:32db4840623ad495a9d2a5',
    messagingSenderId: '25308580160',
    projectId: 'iotsample-4c1e6',
    authDomain: 'iotsample-4c1e6.firebaseapp.com',
    databaseURL: 'https://iotsample-4c1e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsample-4c1e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1TOTWeHtTiEo3mvrHvH6XsSwBYCXpjU',
    appId: '1:25308580160:android:8bc09c91bebe25cfa9d2a5',
    messagingSenderId: '25308580160',
    projectId: 'iotsample-4c1e6',
    databaseURL: 'https://iotsample-4c1e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsample-4c1e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLHN6D24AIaiTJGnwcJNqUfkX6ywpPSGs',
    appId: '1:25308580160:ios:73c9d7ef3162a13ba9d2a5',
    messagingSenderId: '25308580160',
    projectId: 'iotsample-4c1e6',
    databaseURL: 'https://iotsample-4c1e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsample-4c1e6.firebasestorage.app',
    iosBundleId: 'com.example.gasguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLHN6D24AIaiTJGnwcJNqUfkX6ywpPSGs',
    appId: '1:25308580160:ios:73c9d7ef3162a13ba9d2a5',
    messagingSenderId: '25308580160',
    projectId: 'iotsample-4c1e6',
    databaseURL: 'https://iotsample-4c1e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsample-4c1e6.firebasestorage.app',
    iosBundleId: 'com.example.gasguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCLs2aFsjtWCSRsdv_vwQdMNAG8JEZDHQ',
    appId: '1:25308580160:web:24dceed3384180eda9d2a5',
    messagingSenderId: '25308580160',
    projectId: 'iotsample-4c1e6',
    authDomain: 'iotsample-4c1e6.firebaseapp.com',
    databaseURL: 'https://iotsample-4c1e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsample-4c1e6.firebasestorage.app',
  );
}
